"""create academic system tables

Revision ID: 4937fbda7fc1
Revises: 
Create Date: 2026-08-23 00:16:32.526177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4937fbda7fc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_term', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_academic_term', ['academic_year', 'semester'])

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_student_course', ['student_id', 'course_id'])

    with op.batch_alter_table('student_assessment_result', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_student_assessment_result', ['enrollment_id', 'assessment_id'])

    with op.batch_alter_table('student_question_result', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_student_question_result', ['enrollment_id', 'question_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_question_result', schema=None) as batch_op:
        batch_op.drop_constraint('unique_student_question_result', type_='unique')

    with op.batch_alter_table('student_assessment_result', schema=None) as batch_op:
        batch_op.drop_constraint('unique_student_assessment_result', type_='unique')

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_constraint('unique_student_course', type_='unique')

    with op.batch_alter_table('academic_term', schema=None) as batch_op:
        batch_op.drop_constraint('unique_academic_term', type_='unique')

    # ### end Alembic commands ###
