"""add assessment question clo mapping

Revision ID: a204b44736ee
Revises: 4937fbda7fc1
Create Date: 2026-08-24 01:49:00.631514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a204b44736ee'
down_revision = '4937fbda7fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('clo', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_clo_code_per_course', ['course_id', 'clo_code'])

    with op.batch_alter_table('question_clo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('question_clo_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('question_clo_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'clo', ['clo_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_clo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('question_clo_ibfk_1'), 'question', ['question_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('question_clo_ibfk_2'), 'clo', ['clo_id'], ['id'])

    with op.batch_alter_table('clo', schema=None) as batch_op:
        batch_op.drop_constraint('unique_clo_code_per_course', type_='unique')

    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_column('assessment_type')

    # ### end Alembic commands ###
